-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 23:57:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FindenDataBase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FindenDataBase` ;

-- -----------------------------------------------------
-- Schema FindenDataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FindenDataBase` DEFAULT CHARACTER SET utf8 ;
USE `FindenDataBase` ;

-- -----------------------------------------------------
-- Table `FindenDataBase`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`User` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `FindenDataBase`.`User` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`Building` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `FindenDataBase`.`Building` (`name` ASC) VISIBLE;

CREATE UNIQUE INDEX `number_UNIQUE` ON `FindenDataBase`.`Building` (`number` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`Floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`Floor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `Building_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Building_Id`),
  CONSTRAINT `fk_Floor_Building1`
    FOREIGN KEY (`Building_Id`)
    REFERENCES `FindenDataBase`.`Building` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Floor_Building1_idx` ON `FindenDataBase`.`Floor` (`Building_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`Plane` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `dateUpload` DATE NOT NULL,
  `version` FLOAT NULL,
  `state` INT NOT NULL,
  `observation` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `dateApproval` DATE NULL,
  `dir` VARCHAR(255) NOT NULL,
  `Floor_Id` INT NOT NULL,
  `Floor_Building_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Floor_Id`, `Floor_Building_Id`),
  CONSTRAINT `fk_Plane_Floor1`
    FOREIGN KEY (`Floor_Id` , `Floor_Building_Id`)
    REFERENCES `FindenDataBase`.`Floor` (`Id` , `Building_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plane_Floor1_idx` ON `FindenDataBase`.`Plane` (`Floor_Id` ASC, `Floor_Building_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`PlaneXUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`PlaneXUser` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `User_Id` INT NOT NULL,
  `Plane_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `User_Id`, `Plane_Id`),
  CONSTRAINT `fk_PlaneXUser_User`
    FOREIGN KEY (`User_Id`)
    REFERENCES `FindenDataBase`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlaneXUser_Plane1`
    FOREIGN KEY (`Plane_Id`)
    REFERENCES `FindenDataBase`.`Plane` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PlaneXUser_User_idx` ON `FindenDataBase`.`PlaneXUser` (`User_Id` ASC) VISIBLE;

CREATE INDEX `fk_PlaneXUser_Plane1_idx` ON `FindenDataBase`.`PlaneXUser` (`Plane_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`WiringCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`WiringCenter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idWiringCenter` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `Floor_Id` INT NULL,
  `Floor_Building_Id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_WritingCenter_Floor1`
    FOREIGN KEY (`Floor_Id` , `Floor_Building_Id`)
    REFERENCES `FindenDataBase`.`Floor` (`Id` , `Building_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `FindenDataBase`.`WiringCenter` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `idWirtingCenter_UNIQUE` ON `FindenDataBase`.`WiringCenter` (`idWiringCenter` ASC) VISIBLE;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `FindenDataBase`.`WiringCenter` (`name` ASC) VISIBLE;

CREATE INDEX `fk_WritingCenter_Floor1_idx` ON `FindenDataBase`.`WiringCenter` (`Floor_Id` ASC, `Floor_Building_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`Switch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`Switch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `indication` INT NOT NULL,
  `WritingCenter_id` INT NOT NULL,
  `NumeroSwitch` INT NULL,
  PRIMARY KEY (`id`, `WritingCenter_id`),
  CONSTRAINT `fk_Switch_WritingCenter1`
    FOREIGN KEY (`WritingCenter_id`)
    REFERENCES `FindenDataBase`.`WiringCenter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Switch_WritingCenter1_idx` ON `FindenDataBase`.`Switch` (`WritingCenter_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `FindenDataBase`.`Port`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FindenDataBase`.`Port` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `portInSwitch` INT NULL,
  `type` INT NOT NULL,
  `Floor_Id` INT NOT NULL,
  `Floor_Building_Id` INT NOT NULL,
  `Switch_id` INT NULL,
  `Switch_WritingCenter_id` INT NULL,
  PRIMARY KEY (`Id`, `Floor_Id`, `Floor_Building_Id`),
  CONSTRAINT `fk_Port_Floor1`
    FOREIGN KEY (`Floor_Id` , `Floor_Building_Id`)
    REFERENCES `FindenDataBase`.`Floor` (`Id` , `Building_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Port_Switch1`
    FOREIGN KEY (`Switch_id` , `Switch_WritingCenter_id`)
    REFERENCES `FindenDataBase`.`Switch` (`id` , `WritingCenter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `FindenDataBase`.`Port` (`name` ASC) VISIBLE;

CREATE INDEX `fk_Port_Floor1_idx` ON `FindenDataBase`.`Port` (`Floor_Id` ASC, `Floor_Building_Id` ASC) VISIBLE;

CREATE INDEX `fk_Port_Switch1_idx` ON `FindenDataBase`.`Port` (`Switch_id` ASC, `Switch_WritingCenter_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
